const PROJECT_DATA =[
{ "id": "ECE001", "name": "Solar Peizo Hybrid Power Charging System – ECE001", "category": "Renewable Energy", "technology": "Embedded + Power Electronics" },
{ "id": "ECE002", "name": "Zigbee Based Room Temperature Controller Project – ECE002", "category": "IoT", "technology": "Embedded + Zigbee" },
{ "id": "ECE003", "name": "Load Sensing Seats With Lights Fan Control – ECE003", "category": "Automation", "technology": "Embedded Systems" },
{ "id": "ECE004", "name": "Secure Fingerprint Bank Locker With Image Capture – ECE004", "category": "Security", "technology": "Embedded + Biometrics + Camera" },
{ "id": "ECE005", "name": "Accurate Room Temperature Controller Project – ECE005", "category": "Automation", "technology": "Embedded + Sensors" },
{ "id": "ECE006", "name": "High Performance Hovercraft With Power Turning – ECE006", "category": "Robotics", "technology": "Embedded + Motor Control" },
{ "id": "ECE007", "name": "Smart Solar Grass Cutter With Lawn Coverage – ECE007", "category": "Robotics", "technology": "Embedded + Solar + Automation" },
{ "id": "ECE008", "name": "PC Based Home Automation – ECE008", "category": "Automation", "technology": "Embedded + PC Interface" },
{ "id": "ECE009", "name": "Advanced Military Spying & Bomb Disposal Robot – ECE009", "category": "Robotics", "technology": "Embedded + RF + Camera" },
{ "id": "ECE010", "name": "Human Speed Detection Project – ECE010", "category": "Embedded", "technology": "Sensors + Microcontroller" },
{ "id": "ECE011", "name": "Hovercraft Controlled By Android – ECE011", "category": "Robotics", "technology": "Embedded + Android + Bluetooth" },
{ "id": "ECE012", "name": "Fully Automated Solar Grass Cutter – ECE012", "category": "Robotics", "technology": "Embedded + Solar" },
{ "id": "ECE013", "name": "Machine Overheat Detection With Alert – ECE013", "category": "Industrial", "technology": "Temperature Sensors + Embedded" },
{ "id": "ECE014", "name": "RF Controlled Spy Robot With Night Vision Camera – ECE014", "category": "Robotics", "technology": "RF + Camera + Embedded" },
{ "id": "ECE015", "name": "GSM Based Industry Protection System – ECE015", "category": "Security", "technology": "Embedded + GSM" },
{ "id": "ECE016", "name": "Automated Visitor Counter With 7 Segment Display – ECE016", "category": "Embedded", "technology": "Embedded + Display" },
{ "id": "ECE017", "name": "Vehicle Theft Detection With Remote Engine Locking – ECE017", "category": "Automotive Security", "technology": "GSM + Embedded" },
{ "id": "ECE018", "name": "Automated Elevator With Overload Alert – ECE018", "category": "Automation", "technology": "Sensors + Embedded" },
{ "id": "ECE019", "name": "GSM Based Weather Reporting System – ECE019", "category": "IoT", "technology": "GSM + Sensors" },
{ "id": "ECE020", "name": "Fingerprint Authenticated Device Switcher – ECE020", "category": "Security", "technology": "Biometrics + Embedded" },
{ "id": "ECE021", "name": "Fingerprint Based Exam Hall Authentication – ECE021", "category": "Security", "technology": "Biometrics + Embedded" },
{ "id": "ECE022", "name": "Zigbee Based Wireless Home Security System – ECE022", "category": "IoT", "technology": "Zigbee + Embedded" },
{ "id": "ECE023", "name": "Intelligent Surveillance and Night Patrolling Drone – ECE023", "category": "Drone", "technology": "Embedded + Camera + Wireless" },
{ "id": "ECE024", "name": "Automatic Waste Segregation System – ECE024", "category": "Automation", "technology": "Sensors + Embedded" },
{ "id": "ECE025", "name": "Arduino Based Snake Robot Controlled Using Android – ECE025", "category": "Robotics", "technology": "Arduino + Android" },
{ "id": "ECE026", "name": "Garbage Collection Robot Using Wireless Communication – ECE026", "category": "Robotics", "technology": "Wireless + Embedded" },
{ "id": "ECE027", "name": "Smart Door Receptionist With Smart Lock – ECE027", "category": "IoT", "technology": "Embedded + Smart Lock" },
{ "id": "ECE028", "name": "Auto Selection of Available Phase in 3 Phase Supply – ECE028", "category": "Power Systems", "technology": "Power Electronics + Embedded" },
{ "id": "ECE029", "name": "ACPWM Control System for Induction Motor Using AVR – ECE029", "category": "Motor Control", "technology": "AVR + PWM" },
{ "id": "ECE030", "name": "Greenhouse Monitoring and Control System Using IoT – ECE030", "category": "IoT", "technology": "Sensors + WiFi" },
{ "id": "ECE031", "name": "IOT Based Coal Mine Safety Monitoring and Alerting System – ECE031", "category": "IoT", "technology": "Sensors + WiFi + Embedded" },
{ "id": "ECE032", "name": "Advanced Automatic Self-Car Parking Using Arduino – ECE032", "category": "Automation", "technology": "Arduino + Ultrasonic Sensors" },
{ "id": "ECE033", "name": "IOT Based Heart Monitoring System Using ECG – ECE033", "category": "Medical", "technology": "ECG Sensor + IoT + Embedded" },
{ "id": "ECE034", "name": "Smart Stand-up Wheelchair Using Raspberry Pi & RF – ECE034", "category": "Medical", "technology": "Raspberry Pi + RF" },
{ "id": "ECE035", "name": "Arduino Based Autonomous Fire Fighting Robot – ECE035", "category": "Robotics", "technology": "Arduino + Sensors" },
{ "id": "ECE036", "name": "Dual Axis Solar Tracking System With Weather Sensor – ECE036", "category": "Renewable Energy", "technology": "Solar + Embedded + Sensors" },
{ "id": "ECE037", "name": "Android Controlled Automobile – ECE037", "category": "Automotive", "technology": "Android + Bluetooth + Embedded" },
{ "id": "ECE038", "name": "Home Automation Using Android – ECE038", "category": "IoT", "technology": "Android + Embedded + WiFi" },
{ "id": "ECE039", "name": "Zigbee Based Secure Wireless Communication Using AES – ECE039", "category": "Communication", "technology": "Zigbee + AES Encryption" },
{ "id": "ECE040", "name": "Voice Controlled Robotic Vehicle – ECE040", "category": "Robotics", "technology": "Voice Recognition + Embedded" },
{ "id": "ECE041", "name": "Pesticide Sprayer Spider Robot With Grass Cutter – ECE041", "category": "Agriculture Robotics", "technology": "Embedded + Motor Control" },
{ "id": "ECE042", "name": "Smart Shopping Trolley That Follows Customer – ECE042", "category": "Automation", "technology": "RFID + Embedded + Sensors" },
{ "id": "ECE043", "name": "IR Wireless Underwater Communication System – ECE043", "category": "Communication", "technology": "IR + Embedded" },
{ "id": "ECE044", "name": "Advanced Footstep Power Generation System Using RFID – ECE044", "category": "Renewable Energy", "technology": "Piezo + RFID + Embedded" },
{ "id": "ECE045", "name": "Induction Motor Speed Controller Project – ECE045", "category": "Motor Control", "technology": "PWM + Embedded" },
{ "id": "ECE046", "name": "Arduino Alcohol Sense Engine Lock – ECE046", "category": "Automotive Safety", "technology": "Arduino + Gas Sensor" },
{ "id": "ECE047", "name": "Arduino Covid Disinfection Box – ECE047", "category": "Medical", "technology": "Arduino + UV Control" },
{ "id": "ECE048", "name": "Arduino Based System To Measure Solar Power – ECE048", "category": "Renewable Energy", "technology": "Arduino + Sensors" },
{ "id": "ECE049", "name": "Hybrid Inverter With Solar Battery Charging – ECE049", "category": "Power Electronics", "technology": "Inverter + Solar + Embedded" },
{ "id": "ECE050", "name": "Fingerprint Based Bank Locker System – ECE050", "category": "Security", "technology": "Biometrics + Embedded" },
{ "id": "ECE051", "name": "Face Recognition Door Lock System Using Raspberry Pi – ECE051", "category": "Security", "technology": "Raspberry Pi + OpenCV" },
{ "id": "ECE052", "name": "Prepaid Energy Meter With Theft Detection – ECE052", "category": "Power Systems", "technology": "Energy Meter + GSM + Embedded" },
{ "id": "ECE053", "name": "Programmable Omni Direction Robotic Arm Vehicle – ECE053", "category": "Robotics", "technology": "Embedded + Servo Control" },
{ "id": "ECE054", "name": "Smart Room Temperature Controller Atmega – ECE054", "category": "Automation", "technology": "Atmega + Sensors" },
{ "id": "ECE055", "name": "Ultrasonic Radar Project – ECE055", "category": "Embedded", "technology": "Ultrasonic + Microcontroller" },
{ "id": "ECE056", "name": "IOT Irrigation Monitoring & Controller System – ECE056", "category": "IoT", "technology": "Soil Sensor + WiFi" },
{ "id": "ECE057", "name": "Car Safety System With Airbag Notification – ECE057", "category": "Automotive Safety", "technology": "Sensors + GSM" },
{ "id": "ECE058", "name": "Automatic Noise Level Monitor & Controller System – ECE058", "category": "Industrial", "technology": "Sound Sensor + Embedded" },
{ "id": "ECE059", "name": "Induction Motor Controller and Protection System – ECE059", "category": "Motor Control", "technology": "Embedded + Protection Circuits" },
{ "id": "ECE060", "name": "IOT Covid Patient Health Monitor In Quarantine – ECE060", "category": "Medical IoT", "technology": "Sensors + IoT + Embedded" },
{ "id": "ECE061", "name": "Smart Wireless Battery Charging With Charge Monitor Project – ECE061", "category": "Power Electronics", "technology": "Wireless Charging + Embedded" },
{ "id": "ECE062", "name": "DIY Bluetooth Gamepad for Android Gaming – ECE062", "category": "Embedded", "technology": "Bluetooth + Microcontroller" },
{ "id": "ECE063", "name": "IOT Circuit Breaker Project – ECE063", "category": "IoT", "technology": "Embedded + IoT + Relay Control" },
{ "id": "ECE064", "name": "Third Eye For Blind Ultrasonic Vibrator Glove – ECE064", "category": "Assistive Technology", "technology": "Ultrasonic Sensor + Embedded" },
{ "id": "ECE065", "name": "Automatic Road Reflector Light – ECE065", "category": "Automation", "technology": "LDR + Embedded" },
{ "id": "ECE066", "name": "Arduino Ultrasonic Sonar Radar Monitor Project – ECE066", "category": "Embedded", "technology": "Arduino + Ultrasonic Sensor" },
{ "id": "ECE067", "name": "Remote Control Plant Watering System Using 8051 – ECE067", "category": "Agriculture IoT", "technology": "8051 + Sensors" },
{ "id": "ECE068", "name": "Women Safety Night Patrolling Robot – ECE068", "category": "Robotics", "technology": "Embedded + Wireless + Camera" },
{ "id": "ECE069", "name": "IOT Mining Tracking & Worker Safety Helmet – ECE069", "category": "Industrial IoT", "technology": "Sensors + IoT + Embedded" },
{ "id": "ECE070", "name": "Auto Baby Cry Detector Sleep Music Player PIC – ECE070", "category": "Embedded", "technology": "PIC + Sound Sensor" },
{ "id": "ECE071", "name": "Auto Water Pump Switcher – ECE071", "category": "Automation", "technology": "Embedded + Water Level Sensor" },
{ "id": "ECE072", "name": "Auto Billing Mall Shopping Cart 8051 – ECE072", "category": "Automation", "technology": "8051 + RFID" },
{ "id": "ECE073", "name": "IOT Flood Monitoring & Alerting System Using Raspberry Pi – ECE073", "category": "IoT", "technology": "Raspberry Pi + Sensors" },
{ "id": "ECE074", "name": "EV BMS With Charge Monitor and Fire Protection – ECE074", "category": "Automotive", "technology": "Battery Management + Embedded" },
{ "id": "ECE075", "name": "IOT Garbage Monitoring Using Raspberry Pi – ECE075", "category": "IoT", "technology": "Raspberry Pi + Sensors" },
{ "id": "ECE076", "name": "Fingerprint Vehicle Starter Project – ECE076", "category": "Automotive Security", "technology": "Biometrics + Embedded" },
{ "id": "ECE077", "name": "TV Remote Controlled Home Automation PIC – ECE077", "category": "Automation", "technology": "PIC + IR Sensor" },
{ "id": "ECE078", "name": "IOT Based ICU Patient Monitoring System – ECE078", "category": "Medical IoT", "technology": "Sensors + IoT + Embedded" },
{ "id": "ECE079", "name": "Motion Based Door Opener With Metal Detector – ECE079", "category": "Security", "technology": "Motion Sensor + Metal Detector" },
{ "id": "ECE080", "name": "Automatic Light Intensity Controller By External Light Sensing – ECE080", "category": "Automation", "technology": "LDR + Embedded" },
{ "id": "ECE081", "name": "Vehicle Movement Based Street Lights With External Light Sensing – ECE081", "category": "Smart City", "technology": "Sensors + Embedded" },
{ "id": "ECE082", "name": "Traffic Density Control With Android Override Using AVR – ECE082", "category": "Smart City", "technology": "AVR + Android" },
{ "id": "ECE083", "name": "Alcohol Sensing Alert With Engine Locking Project – ECE083", "category": "Automotive Safety", "technology": "Gas Sensor + Embedded" },
{ "id": "ECE084", "name": "DIY Power Bank With Plasma Lighter – ECE084", "category": "Power Electronics", "technology": "Battery + Charging Circuit" },
{ "id": "ECE085", "name": "Path Planner Robot For Indoor Positioning – ECE085", "category": "Robotics", "technology": "Embedded + Sensors" },
{ "id": "ECE086", "name": "WiFi Based Secure Wireless Communication Using RSA – ECE086", "category": "Communication", "technology": "WiFi + RSA Encryption" },
{ "id": "ECE087", "name": "IOT Car Parking System – ECE087", "category": "IoT", "technology": "Sensors + IoT + Embedded" },
{ "id": "ECE088", "name": "Solar Powered Battery Charging With Reverse Current Protection – ECE088", "category": "Renewable Energy", "technology": "Solar + Protection Circuit" },
{ "id": "ECE089", "name": "Multi Robot Coordination For Swarm Robotics – ECE089", "category": "Robotics", "technology": "Embedded + Wireless Communication" },
{ "id": "ECE090", "name": "Wearable Health Monitoring System Project – ECE090", "category": "Medical", "technology": "Sensors + Embedded" },
{ "id": "ECE091", "name": "Automated Night Lighting System – ECE091", "category": "Automation", "technology": "LDR + Embedded" },
{ "id": "ECE092", "name": "Zigbee Based Gas Fire Detection System – ECE092", "category": "IoT", "technology": "Zigbee + Gas Sensor" },
{ "id": "ECE093", "name": "Short Circuit Indicator Project – ECE093", "category": "Power Systems", "technology": "Protection Circuit + Embedded" },
{ "id": "ECE094", "name": "Sun Tracking Solar Panel Using Arduino – ECE094", "category": "Renewable Energy", "technology": "Arduino + Solar + Sensors" },
{ "id": "ECE095", "name": "Object Tracker & Follower Robot Using Raspberry Pi – ECE095", "category": "Robotics", "technology": "Raspberry Pi + Camera + OpenCV" },
{ "id": "ECE096", "name": "IOT Smart Energy Grid – ECE096", "category": "Smart Grid", "technology": "IoT + Power Monitoring" },
{ "id": "ECE097", "name": "Bill Prediction & Power Factor Measuring With SMS Alert – ECE097", "category": "Power Systems", "technology": "Energy Meter + GSM" },
{ "id": "ECE098", "name": "Car Accident & Alcohol Detector Recorder Blackbox – ECE098", "category": "Automotive Safety", "technology": "Sensors + Embedded + GSM" },
{ "id": "ECE099", "name": "IOT Weather Reporting System Using Arduino and Raspberry Pi – ECE099", "category": "IoT", "technology": "Arduino + Raspberry Pi + Sensors" },
{ "id": "ECE100", "name": "LiFi Data Transfer System – ECE100", "category": "Communication", "technology": "LiFi + Embedded" },
{ "id": "ECE101", "name": "Ultrasonic Glasses For the Blind – ECE101", "category": "Assistive Technology", "technology": "Ultrasonic Sensor + Embedded" },
{ "id": "ECE102", "name": "Social Distancing ID Card – ECE102", "category": "IoT", "technology": "Proximity Sensor + Embedded" },
{ "id": "ECE103", "name": "Industrial Production Line Counter System – ECE103", "category": "Industrial", "technology": "Embedded + Sensors" },
{ "id": "ECE104", "name": "Pocket Piano Using 555 Timer IC – ECE104", "category": "Electronics", "technology": "555 Timer IC" },
{ "id": "ECE105", "name": "Arduino Powered MP3 Player – ECE105", "category": "Embedded", "technology": "Arduino + Audio Module" },
{ "id": "ECE106", "name": "Portable PM10 PM2.5 Pollution Analyzer – ECE106", "category": "IoT", "technology": "Air Quality Sensor + Embedded" },
{ "id": "ECE107", "name": "Smart Digital School Bell With Timetable Display – ECE107", "category": "Automation", "technology": "RTC + Embedded + Display" },
{ "id": "ECE108", "name": "Arduino Stepper Motor Controller – ECE108", "category": "Motor Control", "technology": "Arduino + Stepper Driver" },
{ "id": "ECE109", "name": "Industrial Production Target Counter Display System – ECE109", "category": "Industrial", "technology": "Embedded + Display" },
{ "id": "ECE110", "name": "Stop and Go Queue Entry Manager System – ECE110", "category": "Automation", "technology": "Sensors + Embedded" },
{ "id": "ECE111", "name": "Digital Car Turning and Braking Indicator – ECE111", "category": "Automotive", "technology": "Embedded + LED Control" },
{ "id": "ECE112", "name": "RFID Token Based Appointment Calling System – ECE112", "category": "Automation", "technology": "RFID + Embedded" },
{ "id": "ECE113", "name": "Digital Nameplate With Visitor Sensing – ECE113", "category": "IoT", "technology": "Motion Sensor + Embedded" },
{ "id": "ECE114", "name": "Wearable Computer With Temperature Distance Sensors – ECE114", "category": "Wearable", "technology": "Sensors + Embedded" },
{ "id": "ECE115", "name": "Weather Imaging CubeSat With Telemetry Transmission – ECE115", "category": "Aerospace", "technology": "Telemetry + Embedded" },
{ "id": "ECE116", "name": "Ebike Speed Controller System – ECE116", "category": "Automotive", "technology": "Motor Driver + Embedded" },
{ "id": "ECE117", "name": "Air Water Pollution Sensing Smart Watch – ECE117", "category": "Wearable", "technology": "Sensors + IoT" },
{ "id": "ECE118", "name": "Solar SeaWeather and Pollution Transmitter Buoy – ECE118", "category": "Marine IoT", "technology": "Solar + Sensors + IoT" },
{ "id": "ECE119", "name": "Coin Operated Water ATM With Bottle Dispenser – ECE119", "category": "Automation", "technology": "Embedded + Coin Acceptor" },
{ "id": "ECE120", "name": "Wearable Oscilloscope Smart Watch – ECE120", "category": "Wearable", "technology": "Embedded + Signal Processing" },
{ "id": "ECE121", "name": "Contactless Switch For 4 Load Switching – ECE121", "category": "Automation", "technology": "Proximity Sensor + Relay" },
{ "id": "ECE122", "name": "Smart Vehicle Headlight Auto Switching – ECE122", "category": "Automotive", "technology": "LDR + Embedded" },
{ "id": "ECE123", "name": "Contactless Gesture Controlled Study Lamp – ECE123", "category": "Automation", "technology": "Gesture Sensor + Embedded" },
{ "id": "ECE124", "name": "Earthquake Monitor and Alerting System – ECE124", "category": "IoT", "technology": "Vibration Sensor + GSM" },
{ "id": "ECE125", "name": "3D Scanner Machine Using Arduino – ECE125", "category": "Embedded", "technology": "Arduino + Sensors" },
{ "id": "ECE126", "name": "4 Slot Coin Operated Cola Vending Machine – ECE126", "category": "Automation", "technology": "Embedded + Coin Acceptor" },
{ "id": "ECE127", "name": "Mobile Phone & Cash UV Disinfector – ECE127", "category": "Medical", "technology": "UV Control + Embedded" },
{ "id": "ECE128", "name": "8 Leg Spider Robot By Theo Jansen Linkage – ECE128", "category": "Robotics", "technology": "Mechanical Linkage + Embedded" },
{ "id": "ECE129", "name": "IOT IV Bag Monitoring and Alert System – ECE129", "category": "Medical IoT", "technology": "Sensors + IoT" },
{ "id": "ECE130", "name": "Portable Induction Cooktop With Time Temperature Settings – ECE130", "category": "Power Electronics", "technology": "Induction Control + Embedded" },
{ "id": "ECE131", "name": "Barcode Scanner & Display Using Arduino – ECE131", "category": "Embedded", "technology": "Arduino + Barcode Scanner" },
{ "id": "ECE132", "name": "Electromagnetic Coil Gun 3 Stage – ECE132", "category": "Electronics", "technology": "High Current Switching + Embedded" },
{ "id": "ECE133", "name": "Gesture Control Bicycle Indicator Gloves – ECE133", "category": "Wearable", "technology": "Gesture Sensor + Embedded" },
{ "id": "ECE134", "name": "Wireless Master Joystick Controller For Robotics – ECE134", "category": "Robotics", "technology": "Wireless + Embedded" },
{ "id": "ECE135", "name": "Automatic Coil Winding Machine – ECE135", "category": "Industrial Automation", "technology": "Motor Control + Embedded" },
{ "id": "ECE136", "name": "Waterproof Action Camera Drone – ECE136", "category": "Drone", "technology": "Embedded + Camera + Wireless" },
{ "id": "ECE137", "name": "IOT Water Pollution Monitor RC Boat – ECE137", "category": "Marine IoT", "technology": "Sensors + IoT + Embedded" },
{ "id": "ECE138", "name": "Voice Controlled Air Purifier – ECE138", "category": "IoT", "technology": "Voice Module + Embedded" },
{ "id": "ECE139", "name": "Automatic Hydroponic Plant Grow Pot – ECE139", "category": "Agriculture IoT", "technology": "Sensors + Embedded" },
{ "id": "ECE140", "name": "Video Calling Recording Smartphone Stand – ECE140", "category": "Embedded", "technology": "Motor Control + Embedded" },
{ "id": "ECE141", "name": "Solar Power Bank With Wireless Charging – ECE141", "category": "Renewable Energy", "technology": "Solar + Wireless Charging" },
{ "id": "ECE142", "name": "Gesture Control Bluetooth Speaker – ECE142", "category": "Embedded", "technology": "Bluetooth + Gesture Sensor" },
{ "id": "ECE143", "name": "Rain Sensing Hands Free Umbrella Bag – ECE143", "category": "Automation", "technology": "Rain Sensor + Embedded" },
{ "id": "ECE144", "name": "LIDAR Micro Drone With Proximity Sensing – ECE144", "category": "Drone", "technology": "LIDAR + Embedded" },
{ "id": "ECE145", "name": "Contactless IOT Doorbell – ECE145", "category": "IoT", "technology": "Proximity Sensor + WiFi" },
{ "id": "ECE146", "name": "RC Underwater Exploration Drone – ECE146", "category": "Drone", "technology": "Wireless + Embedded + Camera" },
{ "id": "ECE147", "name": "Android Powered Juice Vending Machine – ECE147", "category": "Automation", "technology": "Android + Embedded" },
{ "id": "ECE148", "name": "IOT Smart Parking Using RFID – ECE148", "category": "IoT", "technology": "RFID + IoT" },
{ "id": "ECE149", "name": "IOT Syringe Infusion Pump – ECE149", "category": "Medical IoT", "technology": "Embedded + Sensors" },
{ "id": "ECE150", "name": "Programmable Robotic Arm Using Arduino – ECE150", "category": "Robotics", "technology": "Arduino + Servo Control" },
{ "id": "ECE151", "name": "Smart Helmet With Accident Detection & GSM Alert – ECE151", "category": "IoT", "technology": "Accelerometer + GSM + Embedded" },
{ "id": "ECE152", "name": "IoT Based Smart Energy Meter With Billing – ECE152", "category": "IoT", "technology": "Energy Meter + WiFi + Embedded" },
{ "id": "ECE153", "name": "Automatic Railway Gate Control System – ECE153", "category": "Automation", "technology": "IR Sensor + Embedded" },
{ "id": "ECE154", "name": "Smart Blind Stick With GPS Tracking – ECE154", "category": "Assistive Technology", "technology": "Ultrasonic + GPS + GSM" },
{ "id": "ECE155", "name": "IoT Based Smart Irrigation System – ECE155", "category": "Agriculture IoT", "technology": "Soil Sensor + WiFi" },
{ "id": "ECE156", "name": "Home Security System With Face Recognition – ECE156", "category": "Security", "technology": "Camera + AI + Embedded" },
{ "id": "ECE157", "name": "Wireless Power Transfer System – ECE157", "category": "Power Electronics", "technology": "Inductive Coupling" },
{ "id": "ECE158", "name": "Smart Attendance System Using Face Recognition – ECE158", "category": "AI", "technology": "Camera + Machine Learning" },
{ "id": "ECE159", "name": "IoT Based Smart Waste Management – ECE159", "category": "IoT", "technology": "Ultrasonic + WiFi" },
{ "id": "ECE160", "name": "Voice Controlled Home Automation – ECE160", "category": "IoT", "technology": "Voice Module + WiFi" },
{ "id": "ECE161", "name": "GSM Based Water Level Monitoring System – ECE161", "category": "IoT", "technology": "Water Sensor + GSM" },
{ "id": "ECE162", "name": "Automatic Solar Tracker System – ECE162", "category": "Renewable Energy", "technology": "LDR + Motor Control" },
{ "id": "ECE163", "name": "Smart Traffic Light Control System – ECE163", "category": "Automation", "technology": "IR Sensors + Embedded" },
{ "id": "ECE164", "name": "Bluetooth Controlled Robot Car – ECE164", "category": "Robotics", "technology": "Bluetooth + Embedded" },
{ "id": "ECE165", "name": "Fire Fighting Robot With Water Sprayer – ECE165", "category": "Robotics", "technology": "Flame Sensor + Embedded" },
{ "id": "ECE166", "name": "IoT Based Smart Health Monitoring System – ECE166", "category": "Medical IoT", "technology": "Heart Rate + WiFi" },
{ "id": "ECE167", "name": "Smart Door Lock Using RFID – ECE167", "category": "Security", "technology": "RFID + Embedded" },
{ "id": "ECE168", "name": "Automatic Street Light Controller – ECE168", "category": "Automation", "technology": "LDR + Embedded" },
{ "id": "ECE169", "name": "IoT Based Air Quality Monitoring System – ECE169", "category": "IoT", "technology": "Gas Sensor + WiFi" },
{ "id": "ECE170", "name": "Gesture Controlled Robot – ECE170", "category": "Robotics", "technology": "Accelerometer + RF" },
{ "id": "ECE171", "name": "Smart Parking System With IoT – ECE171", "category": "IoT", "technology": "Ultrasonic + WiFi" },
{ "id": "ECE172", "name": "RF Controlled Robotic Arm – ECE172", "category": "Robotics", "technology": "RF Module + Servo" },
{ "id": "ECE173", "name": "Smart Water Quality Monitoring System – ECE173", "category": "IoT", "technology": "pH Sensor + WiFi" },
{ "id": "ECE174", "name": "IoT Based Smart Dustbin – ECE174", "category": "IoT", "technology": "Ultrasonic + Servo" },
{ "id": "ECE175", "name": "Automatic Plant Watering System – ECE175", "category": "Agriculture IoT", "technology": "Soil Moisture + Pump Control" },
{ "id": "ECE176", "name": "Accident Detection And Alert System – ECE176", "category": "Automotive", "technology": "Accelerometer + GSM" },
{ "id": "ECE177", "name": "Digital Voting Machine Using Arduino – ECE177", "category": "Embedded", "technology": "Arduino + Keypad" },
{ "id": "ECE178", "name": "Smart Bus Tracking System – ECE178", "category": "IoT", "technology": "GPS + GSM" },
{ "id": "ECE179", "name": "IoT Based Smart Weather Monitoring – ECE179", "category": "IoT", "technology": "Temperature + Humidity + WiFi" },
{ "id": "ECE180", "name": "Obstacle Avoiding Robot – ECE180", "category": "Robotics", "technology": "Ultrasonic + Embedded" },
{ "id": "ECE181", "name": "Smart Electricity Theft Detection System – ECE181", "category": "IoT", "technology": "Current Sensor + GSM" },
{ "id": "ECE182", "name": "Automatic Toll Collection Using RFID – ECE182", "category": "Automation", "technology": "RFID + Embedded" },
{ "id": "ECE183", "name": "IoT Based Smart Refrigerator Monitoring – ECE183", "category": "IoT", "technology": "Temperature Sensor + WiFi" },
{ "id": "ECE184", "name": "Line Following Robot – ECE184", "category": "Robotics", "technology": "IR Sensor + Embedded" },
{ "id": "ECE185", "name": "Smart Patient Monitoring System – ECE185", "category": "Medical IoT", "technology": "Heart Rate + Temperature + WiFi" },
{ "id": "ECE186", "name": "Wireless Notice Board Using GSM – ECE186", "category": "Communication", "technology": "GSM + Embedded" },
{ "id": "ECE187", "name": "IoT Based Smart Garage Door System – ECE187", "category": "IoT", "technology": "WiFi + Motor Control" },
{ "id": "ECE188", "name": "Smart Intruder Detection Alarm – ECE188", "category": "Security", "technology": "PIR Sensor + GSM" },
{ "id": "ECE189", "name": "IoT Based Smart Flood Monitoring – ECE189", "category": "IoT", "technology": "Water Level Sensor + GSM" },
{ "id": "ECE190", "name": "Bluetooth Based Home Automation – ECE190", "category": "IoT", "technology": "Bluetooth + Relay Control" },
{ "id": "ECE191", "name": "Smart Gas Leakage Detection System – ECE191", "category": "IoT", "technology": "Gas Sensor + GSM" },
{ "id": "ECE192", "name": "IoT Based Smart Mirror – ECE192", "category": "IoT", "technology": "Display + WiFi" },
{ "id": "ECE193", "name": "Automatic Room Light Controller – ECE193", "category": "Automation", "technology": "IR Sensor + Relay" },
{ "id": "ECE194", "name": "IoT Based Smart Milk Quality Tester – ECE194", "category": "IoT", "technology": "Sensor + WiFi" },
{ "id": "ECE195", "name": "RFID Based Library Management System – ECE195", "category": "Automation", "technology": "RFID + Embedded" },
{ "id": "ECE196", "name": "IoT Based Smart Helmet With Alcohol Detection – ECE196", "category": "Automotive IoT", "technology": "Alcohol Sensor + GSM" },
{ "id": "ECE197", "name": "Smart Agriculture Monitoring Robot – ECE197", "category": "Agriculture Robotics", "technology": "Sensors + Embedded" },
{ "id": "ECE198", "name": "IoT Based Smart Water Dispenser – ECE198", "category": "IoT", "technology": "Flow Sensor + WiFi" },
{ "id": "ECE199", "name": "Automatic Fire Alarm System – ECE199", "category": "Safety", "technology": "Smoke Sensor + Buzzer" },
{ "id": "ECE200", "name": "IoT Based Smart Street Parking – ECE200", "category": "IoT", "technology": "Ultrasonic + WiFi" },
{ "id": "ECE201", "name": "Smart ECG Monitoring System – ECE201", "category": "Medical IoT", "technology": "ECG Sensor + WiFi" },
{ "id": "ECE202", "name": "IoT Based Smart Water Tank Controller – ECE202", "category": "IoT", "technology": "Level Sensor + WiFi" },
{ "id": "ECE203", "name": "Automatic Solar Grass Cutter – ECE203", "category": "Renewable Energy", "technology": "Solar + Motor Control" },
{ "id": "ECE204", "name": "IoT Based Smart Garbage Monitoring – ECE204", "category": "IoT", "technology": "Ultrasonic + GSM" },
{ "id": "ECE205", "name": "Smart Heartbeat Monitoring System – ECE205", "category": "Medical", "technology": "Pulse Sensor + Display" },
{ "id": "ECE206", "name": "IoT Based Smart Security Camera – ECE206", "category": "Security", "technology": "Camera + WiFi" },
{ "id": "ECE207", "name": "Automatic Water Pump Controller – ECE207", "category": "Automation", "technology": "Level Sensor + Relay" },
{ "id": "ECE208", "name": "IoT Based Smart Farming Vehicle – ECE208", "category": "Agriculture IoT", "technology": "GPS + Sensors" },
{ "id": "ECE209", "name": "Smart Industrial Temperature Monitoring – ECE209", "category": "Industrial IoT", "technology": "Temperature Sensor + WiFi" },
{ "id": "ECE210", "name": "IoT Based Smart Home Energy Management – ECE210", "category": "IoT", "technology": "Energy Meter + WiFi" },
{ "id": "ECE211", "name": "Smart Drone With Live Video Streaming – ECE211", "category": "Drone", "technology": "Camera + Wireless" },
{ "id": "ECE212", "name": "IoT Based Smart Ambulance System – ECE212", "category": "Medical IoT", "technology": "GPS + GSM" },
{ "id": "ECE213", "name": "Automatic Speed Control System For Vehicles – ECE213", "category": "Automotive", "technology": "Ultrasonic + Embedded" },
{ "id": "ECE214", "name": "IoT Based Smart Farming Irrigation – ECE214", "category": "Agriculture IoT", "technology": "Soil Sensor + GSM" },
{ "id": "ECE215", "name": "Smart Anti-Theft Vehicle Tracking – ECE215", "category": "Security", "technology": "GPS + GSM" },
{ "id": "ECE216", "name": "IoT Based Smart Electricity Monitoring – ECE216", "category": "IoT", "technology": "Current Sensor + WiFi" },
{ "id": "ECE217", "name": "Automatic Railway Track Crack Detection – ECE217", "category": "Safety", "technology": "Ultrasonic + Embedded" },
{ "id": "ECE218", "name": "IoT Based Smart Traffic Monitoring – ECE218", "category": "IoT", "technology": "Camera + WiFi" },
{ "id": "ECE219", "name": "Smart Water Leakage Detection System – ECE219", "category": "IoT", "technology": "Water Sensor + GSM" },
{ "id": "ECE220", "name": "IoT Based Smart Office Automation – ECE220", "category": "IoT", "technology": "WiFi + Relay" },
{ "id": "ECE221", "name": "Smart Blind Navigation System – ECE221", "category": "Assistive Technology", "technology": "Ultrasonic + GPS" },
{ "id": "ECE222", "name": "IoT Based Smart Crop Monitoring – ECE222", "category": "Agriculture IoT", "technology": "Sensors + WiFi" },
{ "id": "ECE223", "name": "Automatic LPG Gas Monitoring System – ECE223", "category": "Safety", "technology": "Gas Sensor + GSM" },
{ "id": "ECE224", "name": "IoT Based Smart Vehicle Monitoring – ECE224", "category": "IoT", "technology": "GPS + WiFi" },
{ "id": "ECE225", "name": "Smart Flood Alert System – ECE225", "category": "Safety", "technology": "Water Level Sensor + GSM" },
{ "id": "ECE226", "name": "IoT Based Smart Classroom System – ECE226", "category": "IoT", "technology": "Sensors + WiFi" },
{ "id": "ECE227", "name": "Automatic Temperature Controlled Fan – ECE227", "category": "Automation", "technology": "Temperature Sensor + Relay" },
{ "id": "ECE228", "name": "IoT Based Smart Traffic Density Control – ECE228", "category": "IoT", "technology": "IR Sensors + WiFi" },
{ "id": "ECE229", "name": "Smart Water Meter Monitoring – ECE229", "category": "IoT", "technology": "Flow Sensor + GSM" },
{ "id": "ECE230", "name": "IoT Based Smart Door Monitoring – ECE230", "category": "IoT", "technology": "Magnetic Sensor + WiFi" },
{ "id": "ECE231", "name": "Smart Voice Controlled Wheelchair – ECE231", "category": "Medical Robotics", "technology": "Voice Module + Motor Driver" },
{ "id": "ECE232", "name": "IoT Based Smart Grid Monitoring – ECE232", "category": "Industrial IoT", "technology": "Current Sensor + WiFi" },
{ "id": "ECE233", "name": "Automatic Rain Sensing Car Wiper – ECE233", "category": "Automotive", "technology": "Rain Sensor + Embedded" },
{ "id": "ECE234", "name": "IoT Based Smart Environment Monitoring – ECE234", "category": "IoT", "technology": "Gas + Temperature Sensors" },
{ "id": "ECE235", "name": "Smart Baby Monitoring System – ECE235", "category": "Medical IoT", "technology": "Sound Sensor + GSM" },
{ "id": "ECE236", "name": "IoT Based Smart Bus Stop Display – ECE236", "category": "IoT", "technology": "Display + WiFi" },
{ "id": "ECE237", "name": "Automatic Smart Irrigation Drone – ECE237", "category": "Agriculture Drone", "technology": "GPS + Sprayer System" },
{ "id": "ECE238", "name": "IoT Based Smart Power Saver – ECE238", "category": "IoT", "technology": "Current Sensor + WiFi" },
{ "id": "ECE239", "name": "Smart Garbage Collection Robot – ECE239", "category": "Robotics", "technology": "Embedded + Sensors" },
{ "id": "ECE240", "name": "IoT Based Smart Health Band – ECE240", "category": "Wearable IoT", "technology": "Heart Rate + Bluetooth" },
{ "id": "ECE241", "name": "Smart Solar Water Heater Controller – ECE241", "category": "Renewable Energy", "technology": "Temperature Sensor + Embedded" },
{ "id": "ECE242", "name": "IoT Based Smart Electricity Bill Generator – ECE242", "category": "IoT", "technology": "Energy Meter + GSM" },
{ "id": "ECE243", "name": "Automatic Railway Passenger Alert System – ECE243", "category": "Safety", "technology": "Embedded + GSM" },
{ "id": "ECE244", "name": "IoT Based Smart Fire Monitoring – ECE244", "category": "IoT", "technology": "Smoke Sensor + WiFi" },
{ "id": "ECE245", "name": "Smart Accident Prevention System – ECE245", "category": "Automotive", "technology": "Ultrasonic + Embedded" },
{ "id": "ECE246", "name": "IoT Based Smart Crop Protection – ECE246", "category": "Agriculture IoT", "technology": "Motion Sensor + GSM" },
{ "id": "ECE247", "name": "Automatic Smart Water Fountain – ECE247", "category": "Automation", "technology": "IR Sensor + Pump Control" },
{ "id": "ECE248", "name": "IoT Based Smart Industrial Automation – ECE248", "category": "Industrial IoT", "technology": "Sensors + WiFi" },
{ "id": "ECE249", "name": "Smart Wireless Charging Station – ECE249", "category": "Power Electronics", "technology": "Wireless Charging Module" },
{ "id": "ECE250", "name": "IoT Based Smart Disaster Alert System – ECE250", "category": "IoT", "technology": "Sensors + GSM + WiFi" }
];