const PROJECT_DATA = [
{ "id": "EEE001", "name": "Auto Selection of Available Phase in 3 Phase Supply System", "category": "Power Systems", "technology": "Embedded System" },
{ "id": "EEE002", "name": "ACPWM Control System for Induction Motor using AVR Microcontroller", "category": "Motor Control", "technology": "AVR Microcontroller" },
{ "id": "EEE003", "name": "ATMEGA Microcontroller Based Commercial Power Saver", "category": "Energy Management", "technology": "ATMEGA Microcontroller" },
{ "id": "EEE004", "name": "Smart Watch for Seniors Using Microcontroller", "category": "Healthcare", "technology": "Embedded System" },
{ "id": "EEE005", "name": "Smart Charger Monitoring System", "category": "Power Electronics", "technology": "Arduino" },
{ "id": "EEE006", "name": "Flexible AC Transmission System Using TSR", "category": "Power Systems", "technology": "FACTS Controller" },
{ "id": "EEE007", "name": "Device Load Monitor with Programmable Meter for Energy Audit", "category": "Energy Audit", "technology": "Embedded + Metering" },
{ "id": "EEE008", "name": "Power Meter Billing Plus Load Control Using GSM", "category": "Energy Management", "technology": "GSM + Embedded" },
{ "id": "EEE009", "name": "Monthly Electricity Billing Display with SMS Feature", "category": "Energy Management", "technology": "GSM + Microcontroller" },
{ "id": "EEE010", "name": "Industry Power Consumption Penalty Minimization Using AFPC Unit", "category": "Industrial Power", "technology": "Power Factor Controller" },
{ "id": "EEE011", "name": "Commercial Power Saver Project", "category": "Energy Management", "technology": "Embedded System" },
{ "id": "EEE012", "name": "Solar Powered Battery Charging with Reverse Current Protection", "category": "Renewable Energy", "technology": "Solar + Charge Controller" },
{ "id": "EEE013", "name": "Automated Night Lighting System", "category": "Automation", "technology": "LDR + Microcontroller" },
{ "id": "EEE014", "name": "Clap Based Fan Switching System", "category": "Home Automation", "technology": "Sound Sensor + Relay" },
{ "id": "EEE015", "name": "Wireless Doorbell Calling System", "category": "Wireless Systems", "technology": "RF Module" },
{ "id": "EEE016", "name": "Synchronously Blinking Emergency Light", "category": "Emergency Systems", "technology": "LED Driver Circuit" },
{ "id": "EEE017", "name": "Sound Operated Timer Project", "category": "Automation", "technology": "Sound Sensor + Timer IC" },
{ "id": "EEE018", "name": "Smart Burglar Alarm", "category": "Security", "technology": "Embedded + Sensor" },
{ "id": "EEE019", "name": "Plant Moisture Monitoring System", "category": "Agriculture", "technology": "Soil Sensor + Microcontroller" },
{ "id": "EEE020", "name": "Wireless Cell Phone Detection System", "category": "Security", "technology": "RF Detector Circuit" },
{ "id": "EEE021", "name": "Wireless FM Transmitter Mic", "category": "Communication", "technology": "FM Transmitter Circuit" },
{ "id": "EEE022", "name": "Electronic Watch Dog Project", "category": "Automation", "technology": "Timer Circuit" },
{ "id": "EEE023", "name": "Mini FM Transmission System", "category": "Communication", "technology": "FM Module" },
{ "id": "EEE024", "name": "Auto Electronic School Bell", "category": "Automation", "technology": "RTC + Microcontroller" },
{ "id": "EEE025", "name": "Advanced Wireless Power Transfer System", "category": "Power Electronics", "technology": "Inductive Coupling" },
{ "id": "EEE026", "name": "Overvoltage and Undervoltage Protection System", "category": "Protection Systems", "technology": "Voltage Sensing Circuit" },
{ "id": "EEE027", "name": "Fast Voting Game Project", "category": "Embedded Systems", "technology": "Microcontroller" },
{ "id": "EEE028", "name": "Electronic Water Level Controller Device", "category": "Automation", "technology": "Water Sensor + Relay" },
{ "id": "EEE029", "name": "E Bicycle Locking System", "category": "Security", "technology": "RFID + Microcontroller" },
{ "id": "EEE030", "name": "Automatic Smoke Detector Alarm", "category": "Safety", "technology": "Gas Sensor + Buzzer" },
{ "id": "EEE031", "name": "Spring Assist Piezo Generator", "category": "Renewable Energy", "technology": "Piezoelectric Generator" },
{ "id": "EEE032", "name": "Induction Motor Controller and Protection System", "category": "Motor Control", "technology": "Embedded + Protection Circuit" },
{ "id": "EEE033", "name": "EV BMS with Charge Monitor and Fire Protection", "category": "Electric Vehicles", "technology": "Battery Management System" },
{ "id": "EEE034", "name": "DIY Power Bank with Plasma Lighter", "category": "Consumer Electronics", "technology": "Battery + Converter" },
{ "id": "EEE035", "name": "Solar Wireless Electric Vehicle Charging System", "category": "Electric Vehicles", "technology": "Wireless Power Transfer + Solar" },
{ "id": "EEE036", "name": "Ebike Speed Controller System", "category": "Electric Vehicles", "technology": "Motor Driver + PWM" },
{ "id": "EEE037", "name": "Wearable Oscilloscope Smart Watch", "category": "Electronics", "technology": "Embedded + Display" },
{ "id": "EEE038", "name": "Contactless Switch for 4 Load Switching", "category": "Home Automation", "technology": "IR Sensor + Relay" },
{ "id": "EEE039", "name": "Smart Vehicle Headlight Auto Switching", "category": "Automotive", "technology": "Light Sensor + Controller" },
{ "id": "EEE040", "name": "Contactless Gesture Controlled Study Lamp", "category": "Home Automation", "technology": "Gesture Sensor + Microcontroller" },
{ "id": "EEE041", "name": "Earthquake Monitor and Alerting System", "category": "Safety", "technology": "Vibration Sensor + Microcontroller" },
{ "id": "EEE042", "name": "Video Calling / Recording Smartphone Stand", "category": "Consumer Electronics", "technology": "Embedded System" },
{ "id": "EEE043", "name": "Solar Power Bank with Wireless Charging", "category": "Renewable Energy", "technology": "Solar + Wireless Charging" },
{ "id": "EEE044", "name": "Power Grid Failure Detection Based on Voltage and Frequency Variance", "category": "Power Systems", "technology": "Voltage + Frequency Sensor" },
{ "id": "EEE045", "name": "Three Phase Fault Analysis with Auto Reset on Temporary Fault", "category": "Protection Systems", "technology": "Microcontroller + Relay" },
{ "id": "EEE046", "name": "Induction Motor Timer Using Auto Delta Star Starter", "category": "Motor Control", "technology": "Star-Delta Starter + Timer" },
{ "id": "EEE047", "name": "AC to High Voltage DC Using Voltage Multiplier Circuit", "category": "Power Electronics", "technology": "Voltage Multiplier Circuit" },
{ "id": "EEE048", "name": "Smart Road Safety and Vehicle Accident Prevention for Mountain Roads", "category": "Automotive", "technology": "Sensors + Embedded" },
{ "id": "EEE049", "name": "IoT Based Smart Agriculture Monitoring System", "category": "IoT", "technology": "IoT + Sensors" },
{ "id": "EEE050", "name": "IoT Based Automatic Vehicle Accident Detection and Rescue System", "category": "IoT", "technology": "GPS + GSM + Microcontroller" },
{ "id": "EEE051", "name": "RFID Based Petrol Pump Automation System", "category": "Automation", "technology": "RFID + Microcontroller" },
{ "id": "EEE052", "name": "IoT Based Heart Monitoring System Using ECG", "category": "Healthcare", "technology": "ECG Sensor + IoT" },
{ "id": "EEE053", "name": "IoT Based Anti-Theft Flooring System using Raspberry Pi", "category": "Security", "technology": "Raspberry Pi + IoT" },
{ "id": "EEE054", "name": "Dual Axis Solar Tracking System with Weather Sensor", "category": "Renewable Energy", "technology": "Solar Tracker + Sensors" },
{ "id": "EEE055", "name": "Face Recognition Door Lock System Using Raspberry Pi", "category": "Security", "technology": "Raspberry Pi + Camera" },
{ "id": "EEE056", "name": "Rotating Solar Inverter Project 50W", "category": "Renewable Energy", "technology": "Microcontroller + Inverter" },
{ "id": "EEE057", "name": "Vertical Axis Wind Turbine with Inverter", "category": "Renewable Energy", "technology": "Wind Turbine + Inverter" },
{ "id": "EEE058", "name": "Automatic Road Reflector Light", "category": "Automation", "technology": "LDR + LED" },
{ "id": "EEE059", "name": "Auto Water Pump Switcher", "category": "Automation", "technology": "Water Level Sensor + Relay" },
{ "id": "EEE060", "name": "Grid Tie Rotating Solar Rooftop System ATMEGA", "category": "Renewable Energy", "technology": "ATMEGA + Grid Tie Inverter" },
{ "id": "EEE061", "name": "Induction Motor Speed & Direction Controller", "category": "Motor Control", "technology": "PWM + Driver Circuit" },
{ "id": "EEE062", "name": "Hybrid Inverter with Solar Battery Charging", "category": "Renewable Energy", "technology": "Inverter + Solar Charger" },
{ "id": "EEE063", "name": "Digitally Controlled Home Automation Project", "category": "Home Automation", "technology": "Microcontroller + Relay" },
{ "id": "EEE064", "name": "3 Phase Induction Motor with Soft Start", "category": "Motor Control", "technology": "Soft Starter Circuit" },
{ "id": "EEE065", "name": "Wireless Mobile Charging Project", "category": "Power Electronics", "technology": "Wireless Power Transfer" },
{ "id": "EEE066", "name": "Solar UPS Project", "category": "Renewable Energy", "technology": "Solar + UPS Circuit" },
{ "id": "EEE067", "name": "Power Supply with Auto Switching", "category": "Power Electronics", "technology": "Automatic Transfer Switch" },
{ "id": "EEE068", "name": "Flexible AC Transmission Using TSC", "category": "Power Systems", "technology": "Thyristor Switched Capacitor" },
{ "id": "EEE069", "name": "Switching Load by Touch", "category": "Home Automation", "technology": "Touch Sensor + Relay" },
{ "id": "EEE070", "name": "Emergency Auto LED Light", "category": "Emergency Systems", "technology": "Battery + LED Driver" },
{ "id": "EEE071", "name": "3 Way Failure Analyzer Reset on Temporary Fault Else Permanent Trip", "category": "Protection Systems", "technology": "Fault Detection Circuit" },
{ "id": "EEE072", "name": "Over Voltage Under Voltage Load Protection", "category": "Protection Systems", "technology": "Voltage Monitoring Circuit" },
{ "id": "EEE073", "name": "Protecting Induction Motor from Phase & Temperature", "category": "Motor Protection", "technology": "Temperature + Phase Sensor" },
{ "id": "EEE074", "name": "Generating DC High Voltage Using Marx Generator", "category": "Power Electronics", "technology": "Marx Generator Circuit" },
{ "id": "EEE075", "name": "Mini Windmill Power Generation Project", "category": "Renewable Energy", "technology": "Wind Generator" },
{ "id": "EEE076", "name": "Dual Power Generation Solar Plus Windmill Generator", "category": "Renewable Energy", "technology": "Hybrid Solar + Wind" },
{ "id": "EEE077", "name": "Single Phase Induction Motor with Smooth Start", "category": "Motor Control", "technology": "Soft Start Circuit" },
{ "id": "EEE078", "name": "Checking Phase Sequence of 3 Phase Supply", "category": "Power Systems", "technology": "Phase Sequence Indicator" },
{ "id": "EEE079", "name": "6 Volt DC to 10 Volt DC Converter", "category": "Power Electronics", "technology": "DC-DC Boost Converter" },
{ "id": "EEE080", "name": "Microcontroller Less Four Quadrant DC Motor Control", "category": "Motor Control", "technology": "Analog Control Circuit" },
{ "id": "EEE081", "name": "Smart Wireless Battery Charging with Charge Monitor", "category": "Power Electronics", "technology": "Wireless Charging + Monitor" },
{ "id": "EEE082", "name": "Accurate Room Temperature Controller Project", "category": "Automation", "technology": "Temperature Sensor + Controller" },
{ "id": "EEE083", "name": "Industry Process Automation Using Programmable Switching", "category": "Industrial Automation", "technology": "Programmable Controller" },
{ "id": "EEE084", "name": "Testing Life Cycle of Electrical Loads Using Down Counter", "category": "Testing Systems", "technology": "Counter + Embedded" },
{ "id": "EEE085", "name": "AC Power Strength Controller System", "category": "Power Electronics", "technology": "Triac Control Circuit" },
{ "id": "EEE086", "name": "System to Measure Solar Power", "category": "Renewable Energy", "technology": "Solar Sensor + Metering" },
{ "id": "EEE087", "name": "Controlling Solar Energy Charge", "category": "Renewable Energy", "technology": "Charge Controller" },
{ "id": "EEE088", "name": "Configurable Password Security System", "category": "Security", "technology": "Keypad + Microcontroller" },
{ "id": "EEE089", "name": "Supervisory Controlling Plus Data Acquisition for Remote Industry", "category": "Industrial Automation", "technology": "SCADA System" },
{ "id": "EEE090", "name": "Load Control System Using DTMF", "category": "Automation", "technology": "DTMF Decoder + Relay" },
{ "id": "EEE091", "name": "RPM Display for BLDC Motor with Speed Controller", "category": "Motor Control", "technology": "BLDC Driver + Display" },
{ "id": "EEE092", "name": "Multi Power Supply Using 4 Different Sources for No Break Power", "category": "Power Systems", "technology": "Automatic Source Selector" },
{ "id": "EEE093", "name": "Cycle Switching Without Harmonics for Industrial Power Control", "category": "Power Systems", "technology": "Harmonic Control Circuit" },
{ "id": "EEE094", "name": "AC Power Controller with Programmable Interface", "category": "Power Electronics", "technology": "Programmable Controller" },
{ "id": "EEE095", "name": "Load Shedding Time Management with Programmable Interface", "category": "Energy Management", "technology": "Timer + Controller" },
{ "id": "EEE096", "name": "Lamp Illumination Control with Precision", "category": "Lighting Systems", "technology": "Dimmer Control Circuit" },  
{ "id": "EEE097", "name": "Thermal Modelling of Induction Machine Using Lumped Parameter Model", "category": "Motor Systems", "technology": "Modeling + Simulation" },
{ "id": "EEE098", "name": "Inadequacy of Earthing in Building Structures", "category": "Power Systems", "technology": "Electrical Safety Analysis" },
{ "id": "EEE099", "name": "Fuzzy Time Series Electric Load Forecasting Analysis", "category": "Power Systems", "technology": "Fuzzy Logic" },
{ "id": "EEE100", "name": "Electricity Market Deregulation Challenges Analysis", "category": "Energy Policy", "technology": "Market Modeling" },
{ "id": "EEE101", "name": "Design and Construction of 2KVA Automatic Voltage Regulator", "category": "Power Electronics", "technology": "AVR System" },
{ "id": "EEE102", "name": "Comparative Study of Modern NoSQL Models for Large Scale Websites", "category": "Computer Engineering", "technology": "NoSQL Databases" },
{ "id": "EEE103", "name": "State Space Design of Magnetic Suspension System", "category": "Control Systems", "technology": "State Space Control" },
{ "id": "EEE104", "name": "SMS Based Information Search and Retrieval System", "category": "Communication Systems", "technology": "GSM + Database" },
{ "id": "EEE105", "name": "Design and Construction of 1.5KVA Inverter", "category": "Power Electronics", "technology": "Inverter Design" },
{ "id": "EEE106", "name": "Simulation of Error Correction Codes in Wireless Systems", "category": "Communication Systems", "technology": "MATLAB Simulation" },
{ "id": "EEE107", "name": "Voltage Stability Modeling of Interconnected Power System", "category": "Power Systems", "technology": "Power System Simulation" },
{ "id": "EEE108", "name": "Seasonal Variation of Mobile Radio Propagation Study", "category": "Telecommunications", "technology": "RF Propagation Analysis" },
{ "id": "EEE109", "name": "Resource Reservation Scheme for GSM Network Performance", "category": "Telecommunications", "technology": "Network Optimization" },
{ "id": "EEE110", "name": "Power System Restoration Using Artificial Neural Networks", "category": "Power Systems", "technology": "Artificial Neural Network" },
{ "id": "EEE111", "name": "Policy Framework for Fiber Optic Backbone Implementation", "category": "Telecommunications", "technology": "Network Infrastructure" },
{ "id": "EEE112", "name": "Real-Time Monitoring of Radio Access Network", "category": "Telecommunications", "technology": "Network Monitoring" },
{ "id": "EEE113", "name": "Power Consumption Analysis of Encryption Algorithms in Wireless Devices", "category": "Cyber Security", "technology": "Performance Analysis" },
{ "id": "EEE114", "name": "Software Error Impact on GSM Network Performance", "category": "Telecommunications", "technology": "Network Diagnostics" },
{ "id": "EEE115", "name": "Modeling of Interior Permanent Magnet Motor", "category": "Motor Systems", "technology": "Motor Modeling" },
{ "id": "EEE116", "name": "Pipeline Pressure Drop Modeling and Simulation", "category": "Industrial Systems", "technology": "Fluid Simulation" },
{ "id": "EEE117", "name": "Modeling and Simulation of Standalone Photovoltaic System", "category": "Renewable Energy", "technology": "PV Modeling" },
{ "id": "EEE118", "name": "Modeling of 214MVA Turbo Generator Under Short Circuit", "category": "Power Systems", "technology": "Generator Modeling" },
{ "id": "EEE119", "name": "Load Profiling in Automated Electrical Metering", "category": "Energy Management", "technology": "Data Clustering" },
{ "id": "EEE120", "name": "Alternative Transformer Liquid Dielectrics from Local Materials", "category": "Power Systems", "technology": "Material Analysis" },
{ "id": "EEE121", "name": "Wireless Sensor Based Traffic Light Control System", "category": "IoT", "technology": "Wireless Sensor Network" },
{ "id": "EEE122", "name": "Database Availability Improvement via Fault Monitoring", "category": "Computer Engineering", "technology": "Fault Detection System" },
{ "id": "EEE123", "name": "Energy Efficiency Improvement Using FACTS Device Technique", "category": "Power Systems", "technology": "FACTS Controller" },
{ "id": "EEE124", "name": "Implementation of Unified Power Flow Controller for Voltage Stability", "category": "Power Systems", "technology": "UPFC" },
{ "id": "EEE125", "name": "Student Information Database System Implementation", "category": "Software Systems", "technology": "Database System" },
{ "id": "EEE126", "name": "Home Control Automation Using GSM Communication", "category": "Home Automation", "technology": "GSM + Microcontroller" },
{ "id": "EEE127", "name": "Global Spectrum Allocation and Management Models", "category": "Telecommunications", "technology": "Spectrum Analysis" },
{ "id": "EEE128", "name": "Transmission Line Fault Diagnosis Using Neural Network", "category": "Power Systems", "technology": "Neural Network" },
{ "id": "EEE129", "name": "Quality of Service KPI Evaluation in Mobile Network", "category": "Telecommunications", "technology": "QoS Analysis" },
{ "id": "EEE130", "name": "Cardiotocogram Analysis Using Fuzzy Logic System", "category": "Healthcare", "technology": "Fuzzy Logic" },
{ "id": "EEE131", "name": "Electromagnetic Compatibility Assessment in Dual RF Environment", "category": "Telecommunications", "technology": "EMC Analysis" },
{ "id": "EEE132", "name": "Traffic Analysis of Mobile Switching Centre", "category": "Telecommunications", "technology": "Network Traffic Modeling" },
{ "id": "EEE133", "name": "Rain Attenuation Impact on Ka Band Received Power", "category": "Telecommunications", "technology": "Satellite Propagation Analysis" },
{ "id": "EEE134", "name": "Impact of Node Velocity on Mobile Adhoc Network Performance", "category": "Communication Systems", "technology": "MANET Simulation" },
{ "id": "EEE135", "name": "Design and Construction of Inverter System", "category": "Power Electronics", "technology": "Inverter Design" },
{ "id": "EEE136", "name": "Automatic Voltage Inverter and Battery Charger Construction", "category": "Power Electronics", "technology": "Inverter + Charger Circuit" },
{ "id": "EEE137", "name": "Tele-Alarming Smoke Detection Device Using GSM", "category": "Safety Systems", "technology": "GSM + Smoke Sensor" },
{ "id": "EEE138", "name": "Steady State Security Assessment with Distributed Generation", "category": "Power Systems", "technology": "Power Flow Analysis" },
{ "id": "EEE139", "name": "Space Vector PWM for Multi-Level Diode Clamped Converter", "category": "Power Electronics", "technology": "SVPWM Technique" },
{ "id": "EEE140", "name": "Sliding Mode Direct Torque Control of Three Phase Induction Motor", "category": "Motor Control", "technology": "DTC + Control Theory" },
{ "id": "EEE141", "name": "Switch Network Simulation for Institutional Power System", "category": "Power Systems", "technology": "System Simulation" },
{ "id": "EEE142", "name": "Short Term Electric Power Forecast Using ANN", "category": "Power Systems", "technology": "Artificial Neural Network" },
{ "id": "EEE143", "name": "RFID Based Electronic Toll Plaza System", "category": "Automation", "technology": "RFID + Embedded System" },
{ "id": "EEE144", "name": "Power System Compensation Using Passive and FACTS Controllers", "category": "Power Systems", "technology": "Compensation Techniques" },
{ "id": "EEE145", "name": "Macrocell Propagation Model Analysis", "category": "Telecommunications", "technology": "RF Propagation Modeling" },
{ "id": "EEE146", "name": "Performance Evaluation of Handover in Mobile WiMAX Networks", "category": "Telecommunications", "technology": "Handover Analysis" },
{ "id": "EEE147", "name": "Queuing Behaviour Analysis of ATM Switch Buffer", "category": "Communication Systems", "technology": "Queue Modeling" },
{ "id": "EEE148", "name": "Optimized WLAN Performance Under Saturated Traffic", "category": "Communication Systems", "technology": "Wireless Network Analysis" },
{ "id": "EEE149", "name": "LEO Satellite Downlink Throughput Optimization Using TCM", "category": "Telecommunications", "technology": "Trellis Coded Modulation" },
{ "id": "EEE150", "name": "Open Loop VVVF Control of Three Phase Induction Motor", "category": "Motor Control", "technology": "VVVF Control" },
{ "id": "EEE151", "name": "Monitoring and Control of Three Tier Power Supply", "category": "Power Systems", "technology": "Power Monitoring System" },
{ "id": "EEE152", "name": "Modeling of Compact Fluorescent Lamp for Harmonic Mitigation", "category": "Power Quality", "technology": "Harmonic Analysis" },
{ "id": "EEE153", "name": "Modeling of Self Excited Two Phase Reluctance Generator", "category": "Electrical Machines", "technology": "Machine Modeling" },
{ "id": "EEE154", "name": "Maximum Power Point Tracking of PV Using Adaptive Conductance", "category": "Renewable Energy", "technology": "MPPT Algorithm" },
{ "id": "EEE155", "name": "Line Loss Minimization Using Particle Swarm Optimization", "category": "Power Systems", "technology": "PSO Optimization" },
{ "id": "EEE156", "name": "Wind and Rain Influence on Foliage Radio Wave Channel", "category": "Telecommunications", "technology": "Propagation Modeling" },
{ "id": "EEE157", "name": "Effect of Saliency Ratio on Synchronous Reluctance Generator Performance", "category": "Electrical Machines", "technology": "Machine Analysis" },
{ "id": "EEE158", "name": "Software Security Improvement Using Static and Runtime Analysis", "category": "Cyber Security", "technology": "Static Analysis Tools" },
{ "id": "EEE159", "name": "Concurrency Control Improvement in Distributed Database", "category": "Computer Engineering", "technology": "Database Optimization" },
{ "id": "EEE160", "name": "Automatic Fire Detection and Alarm System Implementation", "category": "Safety Systems", "technology": "Fire Sensor + Alarm Circuit" },
{ "id": "EEE161", "name": "Illumination Design and Simulation for Outdoor Sporting Arenas", "category": "Lighting Systems", "technology": "Lighting Simulation" },
{ "id": "EEE162", "name": "Handover Management in Cellular Communication Systems", "category": "Telecommunications", "technology": "Mobility Management" },
{ "id": "EEE163", "name": "Rainfall Forecasting Using Neuro-Fuzzy Logic Model", "category": "Artificial Intelligence", "technology": "Neuro-Fuzzy System" },
{ "id": "EEE164", "name": "Factors Affecting Power Outage in Nigeria", "category": "Power Systems", "technology": "Statistical Analysis" },
{ "id": "EEE165", "name": "Performance Evaluation of UPFC on Fault Current Limitation", "category": "Power Systems", "technology": "UPFC Simulation" },
{ "id": "EEE166", "name": "Emergency Data Information System for Road Accident Victims", "category": "Healthcare", "technology": "Database + Communication System" },
{ "id": "EEE167", "name": "Electric Power Consumption Reduction in Distribution Network", "category": "Energy Management", "technology": "Load Analysis" },
{ "id": "EEE168", "name": "Effect of Membership Functions in Fuzzy Time Series Forecasting", "category": "Artificial Intelligence", "technology": "Fuzzy Logic Modeling" },
{ "id": "EEE169", "name": "QoS Service Differentiation in IEEE 802.11e EDCA", "category": "Communication Systems", "technology": "Wireless QoS Analysis" },
{ "id": "EEE170", "name": "Development of Monarch Butterfly Optimization Algorithm", "category": "Artificial Intelligence", "technology": "Metaheuristic Optimization" },
{ "id": "EEE171", "name": "Firefly Algorithm for Distributed Generation Planning", "category": "Power Systems", "technology": "Optimization Algorithm" },
{ "id": "EEE172", "name": "Improved Short Term Peak Load Forecasting Model for Nigeria Grid", "category": "Power Systems", "technology": "SARIMA + Neural Network" },
{ "id": "EEE173", "name": "Sensitivity Index Based UPFC Placement Technique", "category": "Power Systems", "technology": "Contingency Analysis" },
{ "id": "EEE174", "name": "Intelligent Mobile Learning System Using Multi Agents", "category": "Software Systems", "technology": "Multi-Agent System" },
{ "id": "EEE175", "name": "Deep Convolutional Neural Network for Object Recognition", "category": "Artificial Intelligence", "technology": "Deep Learning" },
{ "id": "EEE176", "name": "Clonal Selection Algorithm for Multiple Shape Detection", "category": "Artificial Intelligence", "technology": "Evolutionary Algorithm" },
{ "id": "EEE177", "name": "Comparative Analysis of Path Loss Prediction Models", "category": "Telecommunications", "technology": "ANN + Regression Modeling" },
{ "id": "EEE178", "name": "Improved Spectrum Sensing for Cognitive Radio", "category": "Telecommunications", "technology": "Signal Processing" },
{ "id": "EEE179", "name": "Design and Construction of Inverter Type Arc Welding Machine", "category": "Power Electronics", "technology": "Welding Inverter" },
{ "id": "EEE180", "name": "Vehicle Speed Control System Design and Simulation", "category": "Control Systems", "technology": "Control Modeling" },
{ "id": "EEE181", "name": "Design and Installation of 200W Solar Power System", "category": "Renewable Energy", "technology": "Solar Installation" },
{ "id": "EEE182", "name": "Design and Fabrication of Freeze Dryer", "category": "Industrial Systems", "technology": "Thermal Engineering" },
{ "id": "EEE183", "name": "Sound Detector with Alarm System", "category": "Safety Systems", "technology": "Sound Sensor + Alarm" },
{ "id": "EEE184", "name": "Automatic Emergency Light Design and Construction", "category": "Emergency Systems", "technology": "Battery Backup System" },
{ "id": "EEE185", "name": "Vehicle Tracking and Accident Alert System Using GPS and GSM", "category": "IoT", "technology": "GPS + GSM Module" },
{ "id": "EEE186", "name": "20W Wireless Public Address System Construction", "category": "Communication Systems", "technology": "Wireless Audio System" },
{ "id": "EEE187", "name": "Contingency Evaluation of Nigerian 330kV Transmission Grid", "category": "Power Systems", "technology": "Power Flow Study" },
{ "id": "EEE188", "name": "Microcontroller Based Vehicle Speed Alarm", "category": "Automotive", "technology": "Microcontroller + Sensor" },
{ "id": "EEE189", "name": "Automatic Water Level Controller for Tanks", "category": "Automation", "technology": "Water Sensor + Relay" },
{ "id": "EEE190", "name": "Microcontroller Based T-Junction Traffic Light Controller", "category": "Automation", "technology": "Traffic Control System" },
{ "id": "EEE191", "name": "GSM Based Home Automation Using AVR", "category": "Home Automation", "technology": "AVR + GSM" },
{ "id": "EEE192", "name": "6V Rechargeable Lamp Design and Construction", "category": "Consumer Electronics", "technology": "Rechargeable Battery System" },
{ "id": "EEE193", "name": "Business Management System Software", "category": "Software Systems", "technology": "Database Application" },
{ "id": "EEE194", "name": "Transient Stability Enhancement Using UPFC", "category": "Power Systems", "technology": "Stability Analysis" },
{ "id": "EEE195", "name": "ANN Based Cellular Network Predictive Resource Allocation", "category": "Telecommunications", "technology": "Artificial Neural Network" },
{ "id": "EEE196", "name": "Optimization of Inter Cell Handover in GSM Network", "category": "Telecommunications", "technology": "Network Optimization" },
{ "id": "EEE197", "name": "KPI Analysis Model for Mobile Number Portability", "category": "Telecommunications", "technology": "Performance Modeling" },
{ "id": "EEE198", "name": "Impact of Harmattan on Microwave Propagation", "category": "Telecommunications", "technology": "RF Propagation Study" },
{ "id": "EEE199", "name": "Analog to Digital Transition in Broadcasting Systems", "category": "Communication Systems", "technology": "Broadcast Engineering" },
{ "id": "EEE200", "name": "Three Level Inverter Based Static VAR Compensator", "category": "Power Electronics", "technology": "Multilevel Inverter" },
{ "id": "EEE201", "name": "Technical Report on Student Industrial Work Experience Scheme", "category": "Power Systems", "technology": "Industrial Training Report" },
{ "id": "EEE202", "name": "Study of Wind Powered Turbine Generation", "category": "Renewable Energy", "technology": "Wind Energy System" },
{ "id": "EEE203", "name": "Seminar Report on Circuit Breakers", "category": "Power Systems", "technology": "Switchgear Analysis" },
{ "id": "EEE204", "name": "Novel Protection Approach for 132kV High Voltage Power System", "category": "Power Systems", "technology": "Protection Scheme" },
{ "id": "EEE205", "name": "High Performance 8kHz PWM Voltage Fed Inverter for Induction Heating", "category": "Power Electronics", "technology": "PWM Inverter" },
{ "id": "EEE206", "name": "Current Source Inverter Fed Induction Motor Drive", "category": "Motor Control", "technology": "CSI Drive" },
{ "id": "EEE207", "name": "Closed Loop PWM VSI Based Induction Motor Control", "category": "Motor Control", "technology": "VSI + PWM Control" },
{ "id": "EEE208", "name": "Effect of Moisture on California Bearing Ratio of Soil", "category": "Civil Engineering", "technology": "Material Testing" },
{ "id": "EEE209", "name": "Online Information Retrieval System for Civil Servants", "category": "Software Systems", "technology": "Web Based System" },
{ "id": "EEE210", "name": "Improved Forced Island and Load Shedding Scheme", "category": "Power Systems", "technology": "Load Shedding Algorithm" },
{ "id": "EEE211", "name": "Shunt Active Power Filter for Harmonic Reduction", "category": "Power Quality", "technology": "Active Filter + SVPWM" },
{ "id": "EEE212", "name": "Dynamic ATM Handover Resource Reservation System", "category": "Telecommunications", "technology": "ATM Network Optimization" },
{ "id": "EEE213", "name": "Improved PV Array Model with Shading Effects", "category": "Renewable Energy", "technology": "PV Modeling" },
{ "id": "EEE214", "name": "Design and Construction of Automatic Phase Selector", "category": "Power Systems", "technology": "Phase Detection Circuit" },
{ "id": "EEE215", "name": "Design of Solar Lead Acid Battery Charger", "category": "Renewable Energy", "technology": "Charge Controller" },
{ "id": "EEE216", "name": "Wind Solar Hybrid Energy System for Telecom Sites", "category": "Renewable Energy", "technology": "Hybrid Energy System" },
{ "id": "EEE217", "name": "Security Door System Using RF Signal", "category": "Security", "technology": "RF Module + Controller" },
{ "id": "EEE218", "name": "10kVA Solar Supported Inverter with Charge Controller", "category": "Renewable Energy", "technology": "Solar Inverter System" },
{ "id": "EEE219", "name": "Design and Construction of Uninterruptible Power Supply", "category": "Power Electronics", "technology": "UPS System" },
{ "id": "EEE220", "name": "Design and Construction of Smart Fan", "category": "Home Automation", "technology": "Sensor + Microcontroller" },
{ "id": "EEE221", "name": "Automatic Solar Powered Security Lighting System", "category": "Renewable Energy", "technology": "Solar Lighting System" },
{ "id": "EEE222", "name": "Home Energy Management System Design", "category": "Energy Management", "technology": "Smart Meter + Controller" },
{ "id": "EEE223", "name": "GSM Based Energy Meter Design", "category": "Energy Management", "technology": "GSM + Metering" },
{ "id": "EEE224", "name": "Simple Burglar Alarm System Design", "category": "Security", "technology": "Alarm Circuit" },
{ "id": "EEE225", "name": "Bandwidth Resource Allocation in ATM Network", "category": "Telecommunications", "technology": "Network Modeling" },
{ "id": "EEE226", "name": "PVC Conduit Wiring System Construction for Bungalow", "category": "Electrical Installation", "technology": "Wiring Installation" },
{ "id": "EEE227", "name": "Digital AC Power Controller Construction", "category": "Power Electronics", "technology": "AC Controller Circuit" },
{ "id": "EEE228", "name": "Automatic Change Over Switch Construction", "category": "Power Systems", "technology": "Auto Transfer Switch" },
{ "id": "EEE229", "name": "12V Battery Charger Construction", "category": "Power Electronics", "technology": "Battery Charging Circuit" },
{ "id": "EEE230", "name": "Cellular Network Handover Channel Reservation Model Using MATLAB", "category": "Telecommunications", "technology": "MATLAB Simulation" },
{ "id": "EEE231", "name": "Bandwidth Management Using IP Traffic Analysis", "category": "Telecommunications", "technology": "Traffic Analysis" },
{ "id": "EEE232", "name": "Real Property Investment Location Assessment System", "category": "Software Systems", "technology": "Decision Support System" },
{ "id": "EEE233", "name": "CMIP Application in ATM Bandwidth Allocation", "category": "Telecommunications", "technology": "Network Protocol Analysis" },
{ "id": "EEE234", "name": "Insulation Coordination Procedure for Power Equipment", "category": "Power Systems", "technology": "Insulation Analysis" },
{ "id": "EEE235", "name": "Wind Induced Transmission Line Load Assessment", "category": "Power Systems", "technology": "Probabilistic Modeling" },
{ "id": "EEE236", "name": "Assessment of Embedded Power Generation in Nigeria", "category": "Power Systems", "technology": "Distributed Generation Study" },
{ "id": "EEE237", "name": "Fingerprint Image Enhancement Using Wavelet Processing", "category": "Artificial Intelligence", "technology": "Image Processing" },
{ "id": "EEE238", "name": "Web Based Management Information System for Health Insurance Scheme", "category": "Software Systems", "technology": "Web Application" },
{ "id": "EEE239", "name": "Three Factor Authentication Model for Improved Security", "category": "Cyber Security", "technology": "Authentication System" },
{ "id": "EEE240", "name": "Rain Attenuation Study for Ka Band Satellite System", "category": "Telecommunications", "technology": "Satellite Communication Analysis" },
{ "id": "EEE241", "name": "Unified Power Quality Conditioner for Radial Distribution Network", "category": "Power Quality", "technology": "UPQC System" },
{ "id": "EEE242", "name": "Mini Grid Potential Analysis for Nigerian Economy", "category": "Renewable Energy", "technology": "Mini Grid Study" },
{ "id": "EEE243", "name": "Linear Temperature Controller System for Boiler Plant", "category": "Control Systems", "technology": "Temperature Control" },
{ "id": "EEE244", "name": "Hybrid Genetic Artificial Fish Swarm Algorithm for Economic Load Dispatch", "category": "Artificial Intelligence", "technology": "Optimization Algorithm" },
{ "id": "EEE245", "name": "Fuzzy Logic Based Transformer Fault Detection Scheme", "category": "Power Systems", "technology": "Fuzzy Protection System" },
{ "id": "EEE246", "name": "Cuckoo Search Based Distributed Generation Coordination", "category": "Power Systems", "technology": "Optimization Technique" },
{ "id": "EEE247", "name": "Transient Stability Analysis of Nigerian 330kV Power System", "category": "Power Systems", "technology": "Stability Analysis" },
{ "id": "EEE248", "name": "Design and Construction of Electronic Display Unit", "category": "Embedded Systems", "technology": "Microcontroller + Display" }
];


