const PROJECT_DATA =[
  { "id": 1, "name": "LED Advertising Board Based on IoT – E-Circular Notification for Students Through Wi-Fi", "category": "IoT", "technology": "Embedded + WiFi" },
  { "id": 2, "name": "Smart Electricity Meter Using IoT", "category": "IoT", "technology": "Embedded + IoT" },
  { "id": 3, "name": "Smart Street Lights Using IoT", "category": "IoT", "technology": "Embedded + IoT" },
  { "id": 4, "name": "Weather Report Streaming with Graphs Using IoT", "category": "IoT", "technology": "IoT + Cloud" },
  { "id": 5, "name": "Industry Parameters Monitoring and Controlling System Based on Embedded Web Server", "category": "IoT", "technology": "Embedded + Web Server" },
  { "id": 6, "name": "IoT Based Greenhouse Monitoring and Controlling System", "category": "IoT", "technology": "IoT + Sensors" },
  { "id": 7, "name": "IoT Based Home Automation – Smart Way to Control Your Home from Anywhere", "category": "IoT", "technology": "IoT + Automation" },
  { "id": 8, "name": "Vehicle Tracking System Using IoT", "category": "IoT", "technology": "IoT + GPS" },
  { "id": 9, "name": "Automatic and Instantaneous Power Station Power Quality Monitoring System Using IoT", "category": "IoT", "technology": "IoT + Power Monitoring" },
  { "id": 10, "name": "Virtual Caretaker – Online Patient Monitoring System", "category": "IoT", "technology": "IoT + Healthcare" },
  { "id": 11, "name": "Traffic Lights Control System", "category": "IoT", "technology": "Embedded + Automation" },
  { "id": 12, "name": "Cell Phone Tower Base Station Safety and Security System", "category": "IoT", "technology": "IoT + Security" },
  { "id": 13, "name": "Zigbee / RF and Internet Based Advanced Street Light Controlling System", "category": "IoT", "technology": "Zigbee + RF + IoT" },
  { "id": 14, "name": "Wireless Sensor Network for Energy Efficiency", "category": "IoT", "technology": "WSN + IoT" },
  { "id": 15, "name": "Dam Water Level Monitoring System", "category": "IoT", "technology": "IoT + Water Monitoring" },
  { "id": 16, "name": "Women Safety Using IoT", "category": "IoT", "technology": "IoT + GPS + GSM" },
  { "id": 17, "name": "Solid Waste Management System for Smart Cities", "category": "IoT", "technology": "IoT + Smart City" },
  { "id": 18, "name": "Automated Street Light Control and Manhole Monitoring with Fault Detection and Reporting System", "category": "IoT", "technology": "IoT + Monitoring" },
  { "id": 19, "name": "Missing People Identification System Using IoT", "category": "IoT", "technology": "IoT + RFID + GPS" },

  { "id": 20, "name": "Electronic Notice Boards Using RS485 with Operating Distance up to 1000 Meters", "category": "Live Projects", "technology": "Embedded + RS485" },
  { "id": 21, "name": "Efficient Power Saver for Street Lights Using LDR RTC LEDs with Solar Power", "category": "Live Projects", "technology": "Solar + Embedded" },
  { "id": 22, "name": "Railway Station Name Display with Distance Indicator", "category": "Live Projects", "technology": "Embedded Display" },
  { "id": 23, "name": "Wireless Controller for PowerPoint Presentations with Laser Pointer", "category": "Live Projects", "technology": "RF + Embedded" },
  { "id": 24, "name": "Industrial Data Logger Using RS485", "category": "Live Projects", "technology": "Embedded + Data Logger" },
  { "id": 25, "name": "Voice Touch Screen MEMS Controlled Wheelchair for Physically Challenged Persons", "category": "Live Projects", "technology": "MEMS + Embedded" },
  { "id": 26, "name": "Smart Home with Power Saving Security Safety and Automatic Water Tank Control", "category": "Live Projects", "technology": "IoT + Automation" },
  { "id": 27, "name": "Smart Digital Home with Security Safety Power Saving and Power Quality Monitoring", "category": "Live Projects", "technology": "IoT + Power Monitoring" },
  { "id": 28, "name": "Intelligent Train Engine for Accident Avoidance and Automatic Railway Gate Control", "category": "Live Projects", "technology": "Embedded + Safety System" },
  { "id": 29, "name": "Vehicle Theft Control and Accident Location Intimation Through SMS", "category": "Live Projects", "technology": "GSM + GPS" },
  { "id": 30, "name": "Intelligent Traffic Signal Priority System for Ambulances and VIP Vehicles", "category": "Live Projects", "technology": "Embedded + IoT" },

  { "id": 31, "name": "Automatic Marks Sending System to Students Through SMS", "category": "Live Projects", "technology": "GSM + Automation" },
  { "id": 32, "name": "Automated Toll Gate System", "category": "Live Projects", "technology": "RFID + Embedded" },
  { "id": 33, "name": "Electronic Health Card System", "category": "Live Projects", "technology": "RFID + Healthcare" },
  { "id": 34, "name": "Bus Arrival and Departure Automatic Announcement System", "category": "Live Projects", "technology": "Embedded + Audio System" },
  { "id": 35, "name": "Child Safety Management System Using RF Technology", "category": "Live Projects", "technology": "RF + Embedded" },
  { "id": 36, "name": "Advanced Bus Ticketing System with Passenger Alert", "category": "Live Projects", "technology": "RFID + GSM" },
  { "id": 37, "name": "Smart City Monitoring System for Advertisement Hoarding Lights with Failure Indication", "category": "Live Projects", "technology": "IoT + Smart City" },
  { "id": 38, "name": "Railway Station Automation System with Auto Announcements Power Saving and Gate Control", "category": "Live Projects", "technology": "Embedded + Automation" },
  { "id": 39, "name": "Advanced Product Price and Information Display System", "category": "Live Projects", "technology": "Embedded Display" },
  { "id": 40, "name": "Advanced Security Systems for Jewellery Shops and Banks", "category": "Live Projects", "technology": "Embedded + Security" },

  { "id": 41, "name": "Zigbee Based Quiz Answering and Feedback System", "category": "Live Projects", "technology": "Zigbee + Embedded" }

]
